[program:dome-client]
directory=/home/ubuntu/dome-client.js
command=/usr/bin/node src/server.js
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
startsecs=2
startretries=3
user=root
stdout_logfile=/home/ubuntu/dome-client.log
stderr_logfile=/home/ubuntu/dome-client.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
